name: kailo_dashboards
channels:
  - conda-forge
dependencies:
  - folium=0.14.0
  - geopandas=0.12.2
  - jupyterlab=3.5.3
  - jupyterlab-spellchecker=0.7.2
  - matplotlib=3.7.0
  - numpy=1.23.5
  - pandas=1.5.3
  - pip=23.0.1
  - plotly=5.13.1
  - python=3.10.6
  - pip:
    - streamlit
    - flake8==6.0.0
    - pycodestyle_magic==0.5
    - mypy==1.1.1
    - nbqa==1.6.4
