name: kailo_dashboards
channels:
  - conda-forge
dependencies:
  - geopandas=0.9.0
  - matplotlib=3.8.0
  - numpy=1.26.0
  - pandas=2.1.1
  - pip=23.3
  - plotly=5.9.0
  - python=3.10.6
  - pip:
    - streamlit==1.28.2
    - statsmodels==0.14.0
    - odfpy==1.4.1
    - st-pages==0.4.5